### ISSUE TITLE
Feature: Version check

### ISSUE THREAD

**Issue by fperez-eypscap** [DavidBriglio/cordova-clean#1]
This is a great idea and potential time saver. Can you please add package and platform version checking for it to be perfect? Are there any hard problems or is it a matter of comparing the version number in package.json/plugin.xml?

**Comment by DavidBriglio** [comment]
Thank you for the feedback! This is actually the next feature I intended on implementing. This functionality will soon be added to the `sync` command 😃

**Comment by fperez-eypscap** [comment]
Thanks, looking forward to it.

**Comment by DavidBriglio** [comment]
I have added this to version 1.3.0!

**Comment by DavidBriglio** [comment]
Make sure you check out the notes I have made in the README on this subject.
