### ISSUE TITLE
Feature: Variables

### ISSUE THREAD

**Issue by fperez-eypscap** [DavidBriglio/cordova-clean#2]
Some plugins use variables to configure options like Android support libraries revisions or API keys. I don't know if variables are taken into account when installing plugins. Also the sync command could detect changes in this variables to remove and reinstall a certain plugin.

**Comment by DavidBriglio** [comment]
This is a great idea, I will add this in!

**Comment by DavidBriglio** [comment]
I have added this to version 1.3.0!
